### ISSUE TITLE
Water Level Probe Detection

### ISSUE THREAD

**Issue by tmnyhbs** [AnthonyDipilato/EspressoMachine#2]
Hey Anthony,

Create work on this project!  I have a Simonelli Oscar that I am slowly working on compiling code for a full machine for (PID temp control, timed shots with preinfusion, eventually volumetric or weight based shots and a display).  My autofill box crapped out and I was excited to find this project.  I am an espresso machine technician by trade, but even at the discounted prices I get on parts, the Gicar box is still over $100.

I am having an issue where the code detects the fill probe at 1 for only a second, then goes to 0 regardless of if the tank has filled.  I have it connected directly to pin 9.  Is there an addition of anything inline that is needed to get this working properly?  

The water level probe is brand new, and I have replaced all the wires in the fill circuit.  I am wondering if it is a grounding issue on the high voltage side?  

Any input you can provide will be greatly appreciated.

Thanks!

Dave

**Comment by AnthonyDipilato** [comment]
Hello Dave,
You also need to ground the boiler to the arduino, that may be why the
reading is floating.

Are you using my code? If not, you have to set the pinMode to input_pullup
so you don’t need a pull-up resistor.

Let me know if that helps.

Cheers,
Anthony

**Comment by tmnyhbs** [comment]
Ah!  Dumb mistake on my part.  Completely forgot about needing to ground the boiler to the board... (its always the simple stuff).  

I am using your code!  I am going to be integrating it into my code, which is an adapted version of http://playground.arduino.cc/Main/BarebonesPIDForEspresso to use the MAX31685 + RTD-100 probe.  

My end goal is to have Linea PB style controls on the machine -- simple interface of 3 buttons and a display on the front for easy adjustments and readings.  

Thank you for your quick response!

**Comment by AnthonyDipilato** [comment]
That sounds awesome! Let me know how it works out.

Cheers,
Anthony

**Comment by tmnyhbs** [comment]
> That sounds awesome! Let me know how it works out. Cheers, Anthony
> […](#)

https://github.com/daveciepluch/OpenSproV1

Work in progress!  Finally got the autofill circuit running, and then combined it into the project I am working on.

**Comment by AnthonyDipilato** [comment]
It has PID heat control too. Very cool!
